spring:
  cloud:
    function:
      #definition: uppercase|reverse;userCreatedEvent;userUpdatedEvent;userSupplier
      definition: functionRouter
      scan.packages: com.example.functions.functions
      #routing-expression: "headers['type']==userCreatedEvent ? 'userCreatedEvent' : 'userUpdatedEvent'"
#    stream:
#      function:
#        routing:
#          enabled: true
      kafka:
        binder:
          brokers: localhost:9092
          replication-factor: 1
#      bindings:
#        user-in-0:
#          binder: kafka #optional
#          destination: user
#          content-type: text/plain
#          group: user-consumer
#        userSupplier-out-0:
#          destination: user
#          content-type: text/plain


