spring:
  cloud:
    function:
      #definition: uppercase|reverse;userCreatedEvent;userUpdatedEvent;userSupplier
      definition: functionRouter
      #routing-expression: "headers['type']==userCreatedEvent ? 'userCreatedEvent' : 'userUpdatedEvent'"
#    stream:
#      function:
#        routing:
#          enabled: true
      kafka:
        binder:
          brokers: localhost:9092
          replication-factor: 1


