
spring:
  cloud:
    function:
      #definition: uppercase|reverse;userCreatedEvent;userUpdatedEvent;userSupplier
      definition: functionRouter
      scan.packages: com.example.functions.functions
      #routing-expression: "headers['type']==userCreatedEvent ? 'userCreatedEvent' : 'userUpdatedEvent'"
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          replication-factor: 1
      bindings:
        functionRouter-in-0:
          binder: kafka #optional
          destination: user,ticket
          content-type: text/plain
          group: user-consumer
logging:
  level:
    root: INFO
    org.apache.kafka.clients: ERROR

